apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Ejemplo: usuario 'user' codificado en base64
  db_user: dXNlcg== 
  # Ejemplo: contraseña 'password123' codificada en base64
  db_password: cGFzc3dvcmQxMjM=